# Generated by Django 3.2.9 on 2021-11-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalpassport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.CharField(default='flag image', max_length=200),
            preserve_default=False,
        ),
    ]
